// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MijankyalQnnutyun.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace MijankyalQnnutyun.Models.Configurations
{
    public partial class LearningConfiguration : IEntityTypeConfiguration<Learning>
    {
        public void Configure(EntityTypeBuilder<Learning> entity)
        {
            entity.HasKey(e => e.Id).HasName("Learning_pkey");

            entity.ToTable("Learning");

            entity.Property(e => e.Id).UseIdentityAlwaysColumn();
            entity.Property(e => e.Group).HasColumnType("char");
            entity.Property(e => e.Speciality).HasColumnType("char");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Learning> entity);
    }
}
