// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MijankyalQnnutyun.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace MijankyalQnnutyun.Models.Configurations
{
    public partial class StudentConfiguration : IEntityTypeConfiguration<Student>
    {
        public void Configure(EntityTypeBuilder<Student> entity)
        {
            entity.HasKey(e => e.Id).HasName("Students_pkey");

            entity.Property(e => e.Id).UseIdentityAlwaysColumn();
            entity.Property(e => e.Nsf).HasColumnName("NSF");
            entity.Property(e => e.TestColumn).HasColumnType("char");

            entity.HasOne(d => d.Learning).WithMany(p => p.Students)
                .HasForeignKey(d => d.LearningId)
                .HasConstraintName("LearningId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Student> entity);
    }
}
