// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MijankyalQnnutyun.Models;

public partial class Student
{
    public int Id { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public DateOnly? YearOfEnrollment { get; set; }

    public char? Nsf { get; set; }

    public char? City { get; set; }

    public int? LearningId { get; set; }

    public char? TestColumn { get; set; }

    public virtual Learning? Learning { get; set; }
}public class StudentsSeedDataSettings
{
    public List<Student> Students { get; set; }
}